### ISSUE TITLE
hud stat

### ISSUE THREAD

**Issue by frazz1234** [EntityEvolution/ev-hud#12]
So, i use no framework. The healt, body armor and all not sync with the stat player 
The ID stay at 123

i have the last version.

**Comment by BombayV** [comment]
Mmm. This should not be occurring. Can you add `print(state)` after this line.
https://github.com/EntityEvolution/ev-hud/blob/main/client/hud_cl.lua#L88

**Comment by frazz1234** [comment]
still no working

**Comment by BombayV** [comment]
It's not supposed to work, it's supposed to print something.

**Comment by safky24** [comment]
i have the same issue on same players

**Comment by BombayV** [comment]
No response with actual data about the issue.
