### ISSUE TITLE
Config.voiceKey not editable.

### ISSUE THREAD

**Issue by ShiftyGaming** [EntityEvolution/ev-hud#20]
Hi I'm using ESX framework and Mumble-voip. I want to use `Config.voiceKey = 'z'` but it doesn't seem to allow it. everytime I update it it doesn't ingame. it keeps the default H key.

**Comment by ShiftyGaming** [comment]
Changing in the `settings > Keybinds > FiveM > ev-hud` works. One more question though, How can I make it so there is no lag when I'm eating and the bar takes like 5 seconds to update. I want it to be instant.

**Comment by BombayV** [comment]
I answered this in the forum. Read the latest comments.
https://forum.cfx.re/t/release-ev-hud-customizable-standalone-hud/2647626
Sorry the late response.

**Comment by ShiftyGaming** [comment]
Can you specify which reply you send it in?

**Comment by BombayV** [comment]
https://forum.cfx.re/t/release-ev-hud-customizable-standalone-hud/2647626/272?u=xios_bombay
