### ISSUE TITLE
Hide on car

### ISSUE THREAD

**Issue by og23rd** [EntityEvolution/ev-hud#24]
Please hide on car so it doesnt hide car huds thanks for the beautiful hud. <3

**Comment by BombayV** [comment]
You are free to do it yourself 😃

**Comment by og23rd** [comment]
> 

How can i do that? Sorry im not an expert... Is it possible for you to tell me how can i hide the hud while ox_inventory is open please?

**Comment by og23rd** [comment]
Hablas Español?

**Comment by BombayV** [comment]
> > 
> 
> How can i do that? Sorry im not an expert... Is it possible for you to tell me how can i hide the hud while ox_inventory is open please?

You're gonna have to do it yourself. I am currently with very limited time.
