### ISSUE TITLE
Hunger/Thirst 

### ISSUE THREAD

**Issue by Ritbate** [EntityEvolution/ev-hud#5]
Not only me but we have issue we change Config.JS and Config to true with ESX but its not registering.
Es_Extended 1.2.0
Just downloaded Esx_Status

**Comment by BombayV** [comment]
Where did you download it from?

**Comment by Ritbate** [comment]
https://github.com/pizzA0/esx_status
https://github.com/EntityEvolution/ev-hud

**Comment by BombayV** [comment]
Yeah, don't use that esx_status. It's outdated and it doesn't have the trigger. Use this one
[esx_status.zip](https://github.com/EntityEvolution/ev-hud/files/6912113/esx_status.zip)

**Comment by Ritbate** [comment]
> Yeah, don't use that esx_status. It's outdated and it doesn't have the trigger. Use this one
> [esx_status.zip](https://github.com/EntityEvolution/ev-hud/files/6912113/esx_status.zip)

Link is not working

**Comment by Ritbate** [comment]
same with https://github.com/Bammer013/esx_status

**Comment by BombayV** [comment]
oof. Ok. I'll try sending it again. The problem is that it doesn't have the esx_status trigger.

**Comment by BombayV** [comment]
[workplease.zip](https://github.com/EntityEvolution/ev-hud/files/6913009/workplease.zip)

**Comment by Ritbate** [comment]
> [workplease.zip](https://github.com/EntityEvolution/ev-hud/files/6913009/workplease.zip)

Working i will try now

**Comment by BombayV** [comment]
Ok, the other one doesn't have the event either so hopefully this works

**Comment by Ritbate** [comment]
> Ok, the other one doesn't have the event either so hopefully this works

It's working thank you so much!

**Comment by senasiaga** [comment]
I have installed the esx_status given but the hunger and thist still not working. I am using ESX V1 final.

**Comment by BombayV** [comment]
Weird Stuff
